### DISCUSSION TITLE
Propozycja sprzętowa

### DISCUSSION THREAD

**Discussion by jokers1975** [Lewa-Reka/esphome-deye-inverter#2] [Ideas]
Na wstępie gratuluje świetnego kodu.
Chcę zainteresować wszystkich świetnym sprzętem, który nada się idealnie pod projekt falownik-pv-esphome
KAmod ESP32 POW+RS485 to płytka ewaluacyjna wyposażona w moduł Wi-Fi ESP32-WROOM oraz interfejs RS485, zaprojektowana z myślą o zastosowaniach w automatyce domowej i przemysłowej, szczególnie tam, gdzie wymagane są niezawodne połączenia bezprzewodowe oraz przewodowe (RS485, np. w standardzie MODBUS)
To jest polski projekt, jest świetny i warto wspierać swoich. Dlaczego warto? wszystko co nam potrzeba jest zintegrowane, wystarczy wgrać soft i odpalić, wszystkie kable łączymy z falownikiem, nic nie łączymy innego z płytką ESP, żadnego lutowania, żadnej plontaniny kabli, nie każdy jest dobry w lutowaniu itp, tutaj minimalizujemy problemy.
Cena poniżej 90 zł, to naprawdę dobra cena.

Oto gotowe ustawienia dla tej płytki:
```
esp32:
  board: esp32dev
  framework:
    type: arduino

uart:
#  id: mod_bus
  rx_pin: GPIO27
  tx_pin: GPIO25
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
 
modbus:
#  id: sunsynk_modbus
  flow_control_pin: GPIO26  # Poprawna nazwa parametru
  send_wait_time: 200ms
#  uart_id: mod_bus
```

![kamod-esp32-powrs485-plytka-ewaluacyjna-z-modulem-wi-fi-typu-esp32-wroom-i-interfejsem-rs485](https://github.com/user-attachments/assets/c8e099e9-295e-4481-b611-8ab3748c9e32)

**Comment by Lewa-Reka** [comment]
Poprawiłem trochę formatowanie żeby ładniej wyglądało;) Dzięki za kolejną propozycję!:)
Jak wspominałem już parę razy. Sprzęt można dobrać na wiele sposób zależnie od potrzeb. 
Koledzy też proponowali jeszcze LilyGo jako gotowca. Pewnie tak samo dobry wybór jak każdy inny;)

**Comment by pawelkiwi** [comment]
Używam u siebie właśnie tą płytkę. Zadziałała od kopa, oczywiście zmiana pinów i dodatkowe flow_control.

```
uart:
  # Default TX and RX pins, if TTL converter is connected differently, set appropriate pins
  tx_pin: GPIO25
  rx_pin: GPIO27

modbus:
  flow_control_pin: GPIO26 # Uncomment and set appropriate pin if your TTL converter requires it`
```
