### DISCUSSION TITLE
Problem ze znikającymi encjami

### DISCUSSION THREAD

**Discussion by jokers1975** [Lewa-Reka/esphome-deye-inverter#3] [Issues & Problems]
Testowane na falowniku Deye SUN-12kW-SG04LP3-EU
Co kilka minut, na kilkanaście sekund znikają wartości encji, hardwarowo mam to samo, co przy innym wsadzie esphome i poprzednio nie miałem takiego zjawiska więc sądzę że gdzieś jest problem w kodzie.
Czy ten log coś autorowi powie?
<img width="1119" alt="Screenshot at Jun 05 20-04-10" src="https://github.com/user-attachments/assets/ae26021e-9098-4af7-aa7e-3f9fbfcdd0c6" />

**Comment by Lewa-Reka** [comment]
Jaka wersja oprogramowanie falowanika?
Albo z ekranu albo z `sensor.deye_inverter_device_main_firmware_version` można odczytać.

Dodatkowo widzę że zapomniałem też dać znać żeby podnieść baud_rate dla falownika na 19200
W menu falownika: Advanced Settings -> Set. 3 -> Baud Rate na 19200
Po zapisaniu zgaśnie ekran i włączy sie alarm, to normalne. Powinno po chwili wszystko wrócić do normy.

Choć sama zmiana tu raczej nie pomoże. Ale warto wykluczyć.

Sensory znikają bo jak widac po logach on sie restartuje pewnie z uwagi na jakięs błędy.
Warto też odkomentować
```
log:
  level: VERBOSE
```
  
 I zobaczyć co wiecej tam pokazuje w okolicy błędów czy restartów.

**Comment by jokers1975** [comment]
Zmiana prędkości nic nie dała, dalej co chwile znikają encje.
Oto moja wersja firmware:
![IMG_9300](https://github.com/user-attachments/assets/a7f69ecd-d84d-4842-982e-fee3c1412783)

Oto mój konfig:

```
esphome:
  name: deye
  friendly_name: deye

# Set appropriately if using a different board. https://esphome.io/components/#supported-microcontrollers
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
captive_portal:
    
web_server:
  port: 80

switch:
  - platform: restart
    name: "Restart ESP"

substitutions:
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret pv_inverter_api_key
  ota_password: !secret pv_inverter_ota_password
  fallback_password: !secret pv_inverter_fallback_password

  modbus_inverter_address: "0x01" # Default Modbus address, should be changed to match inverter settings

  # Safe Mode parameters for supported inverters
  safe_mode_delay: 600s # Time after which transition to safe mode and setting default operating parameters will occur
  default_maximum_battery_charge_current: "140" # Amps
  default_max_sell_power: "8000" # Watts
  default_system_work_mode: "Zero Export To Load" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "on" # "on", "off"

packages:
  pv_inverter:
    url: https://github.com/Lewa-Reka/esphome-pv-inverter
    refresh: 12h
    files:
      pv_inverter/deye_hybrid_3p_lv.yaml # SG0XLP3 Low Voltage
      # pv_inverter/deye_hybrid_3p_hv.yaml # SG0XHP3 High Voltage

uart:
#  id: mod_bus
  rx_pin: GPIO27
  tx_pin: GPIO25
  baud_rate: 19200
#  data_bits: 8
#  stop_bits: 1
#  parity: EVEN

modbus:
  flow_control_pin: 26
  send_wait_time: 300ms
 ```
